[tool.poetry]
name = "archive_transfer_client"
version = "0.1.0"
description = ""
authors = ["Marcos Gabriel Nunes <mgabriel6643@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.9.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
